### ISSUE TITLE
Got `panic: time: missing Location in call to Time.In` with release `Windows_x86_64_0.3.1`

### ISSUE THREAD

**Issue by Deses** [simulot/immich-go#30]
Got this error using this command:

`immich-go -server=http://192.168.1.130:9210 -key=APIKEY -log-level=INFO upload -google-photos takeout-20230922T153302Z-001.zip 1> immich-go.log 2>&1`

```
immich-go  0.3.1, commit 47283c359f32a4e52e95542382ceea2aa6eca494, built at 2023-10-10T15:23:30Z
Server status: OK
Connected, user: xxxxxxxx@gmail.com
Get server's assets. 0 received
Browsing google take out archive... Done.
0 media scanned, 0 uploaded.
Done.
panic: time: missing Location in call to Time.In

goroutine 9 [running]:
time.Time.In(...)
	/usr/local/go/src/time/time.go:1146
immich-go/assets/gp.googTimeObject.Time({0xc001765730?})
	/home/jfcassan/Dev/immich-go/assets/gp/json.go:65 +0x9b
immich-go/assets/gp.(*Takeout).copyGoogleMDToAsset(0xc00002a750?, 0xc0016f0000, 0x25?)
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:207 +0xb1
immich-go/assets/gp.(*Takeout).checkJSONs(0xc00002a750, {0xc0016d45e6, 0x17}, {0xc0023fd510, 0x1, 0x0?})
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:155 +0x1c5
immich-go/assets/gp.(*Takeout).Browse.func1()
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:123 +0x231
created by immich-go/assets/gp.(*Takeout).Browse in goroutine 1
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:109 +0xb6
```

**Comment by simulot** [comment]
On a mac?

**Comment by Deses** [comment]
On Windows. I said it on the title. 😝

**Comment by simulot** [comment]
Sorry...
Give me some time to spin up a windows VM

**Comment by Turge08** [comment]
Same here:

.\immich-go.exe -log-level=INFO -server=http://10.0.105.152:8080 -key=<APIKEY> upload -create-albums -google-photos takeout-*.zip
immich-go  0.3.2, commit 8d36fff067d39347be9e01706c4b4b78a36d8245, built at 2023-10-10T20:29:36Z
Server status: OK
Connected, user: xxxxxxxx@gmail.com
Get server's assets... 0 received
Browsing google take out archive...Done.
0 media scanned, 0 uploaded.
Done.
panic: time: missing Location in call to Time.In

goroutine 13 [running]:
time.Time.In(...)
        /usr/local/go/src/time/time.go:1146
immich-go/assets/gp.googTimeObject.Time({0xc0025f0980?})
        /home/jfcassan/Dev/immich-go/assets/gp/json.go:65 +0x9b
immich-go/assets/gp.(*Takeout).copyGoogleMDToAsset(0xc0001933e0?, 0xc0045680e0, 0x25?)
        /home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:207 +0xb1
immich-go/assets/gp.(*Takeout).checkJSONs(0xc0001933e0, {0xc0020931a6, 0xc}, {0xc002139010, 0x1, 0x0?})
        /home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:155 +0x1c5
immich-go/assets/gp.(*Takeout).Browse.func1()
        /home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:123 +0x231
created by immich-go/assets/gp.(*Takeout).Browse in goroutine 1
        /home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:109 +0xb6

**Comment by Deses** [comment]
Up, can confirm that 0.3.2 still doesn't work.

```
immich-go  0.3.2, commit 8d36fff067d39347be9e01706c4b4b78a36d8245, built at 2023-10-10T20:29:36Z
Server status: OK
Connected, user: xxxxx@gmail.com
Get server's assets... 0 received
Browsing google take out archive...Done.
panic: time: missing Location in call to Time.In

goroutine 51 [running]:
time.Time.In(...)
	/usr/local/go/src/time/time.go:1146
immich-go/assets/gp.googTimeObject.Time({0xc001f7d520?})
	/home/jfcassan/Dev/immich-go/assets/gp/json.go:65 +0x9b
immich-go/assets/gp.(*Takeout).copyGoogleMDToAsset(0xc0001920c0?, 0xc001278000, 0x1c?)
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:207 +0xb1
immich-go/assets/gp.(*Takeout).checkJSONs(0xc0001920c0, {0xc00203b65d, 0x1e}, {0xc0020441b0, 0x1, 0x0?})
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:155 +0x1c5
immich-go/assets/gp.(*Takeout).Browse.func1()
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:123 +0x231
created by immich-go/assets/gp.(*Takeout).Browse in goroutine 1
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:109 +0xb6

```

**Comment by Deses** [comment]
Yup, can confirm that 0.3.2 still doesn't work.

```
immich-go  0.3.2, commit 8d36fff067d39347be9e01706c4b4b78a36d8245, built at 2023-10-10T20:29:36Z
Server status: OK
Connected, user: xxxxx@gmail.com
Get server's assets... 0 received
Browsing google take out archive...Done.
panic: time: missing Location in call to Time.In

goroutine 51 [running]:
time.Time.In(...)
	/usr/local/go/src/time/time.go:1146
immich-go/assets/gp.googTimeObject.Time({0xc001f7d520?})
	/home/jfcassan/Dev/immich-go/assets/gp/json.go:65 +0x9b
immich-go/assets/gp.(*Takeout).copyGoogleMDToAsset(0xc0001920c0?, 0xc001278000, 0x1c?)
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:207 +0xb1
immich-go/assets/gp.(*Takeout).checkJSONs(0xc0001920c0, {0xc00203b65d, 0x1e}, {0xc0020441b0, 0x1, 0x0?})
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:155 +0x1c5
immich-go/assets/gp.(*Takeout).Browse.func1()
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:123 +0x231
created by immich-go/assets/gp.(*Takeout).Browse in goroutine 1
	/home/jfcassan/Dev/immich-go/assets/gp/googlephotos.go:109 +0xb6

```

Please @simulot, can you reopen this issue?

---

@Turge08 how do you run it in Unraid? User scripts plugin?

**Comment by simulot** [comment]
```
Get server's assets...GetAllAssets, GET, http://192.168.10.17:2283/api/asset, 200 OK
unknown time zone Europe/Paris
```
🤔

**Comment by Turge08** [comment]
@Deses I copied the Linux binary along with the takeout files to one of the unraid shares, opened a shell through the unraid dashboard, added execute permission to the binary (chmod +x) then executed the same command line as on the Windows box

**Comment by simulot** [comment]
fixed. 
👀

**Comment by Deses** [comment]
Paris is saved!

**Comment by simulot** [comment]
> You are going to hate me (and Windows), but:

Not you, but Microsoft. Who at MS took the stupide decision to name the time zone Romance Standard Time...?

**Comment by Nuuki9** [comment]
Similar issue for me, though I'm on standard GMT

```
immich-go  0.3.3, commit 4a2a9a039c828f73f9fa053b019cd25b876f371e, built at 2023-10-11T17:11:35Z
Server status: OK
Connected, user: richard@mines.uk
Get server's assets...GetAllAssets, GET, http://192.168.1.10:8084/api/asset, 200 OK
unknown time zone Europe/London
```

tzutil /g
```
GMT Standard Time
```

Powershell:
```
Id                         : GMT Standard Time
DisplayName                : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
StandardName               : GMT Standard Time
DaylightName               : GMT Summer Time
BaseUtcOffset              : 00:00:00
SupportsDaylightSavingTime : True
```

**Comment by simulot** [comment]
May be this time is the good one 👀

**Comment by Deses** [comment]
Maybe!

I was about to comment the whole list of Windows Timezones but you were faster!

Anyway,
```
tzutil /l
(UTC-12:00) Línea internacional de cambio de fecha
Dateline Standard Time

(UTC-11:00) Hora universal coordinada-11
UTC-11

(UTC-10:00) Hawai
Hawaiian Standard Time

(UTC-10:00) Islas Aleutianas
Aleutian Standard Time

(UTC-09:30) Islas Marquesas
Marquesas Standard Time

(UTC-09:00) Alaska
Alaskan Standard Time

(UTC-09:00) Hora universal coordinada-09
UTC-09

(UTC-08:00) Baja California
Pacific Standard Time (Mexico)

(UTC-08:00) Hora del Pacífico (EE.UU. y Canadá)
Pacific Standard Time

(UTC-08:00) Hora universal coordinada-08
UTC-08

(UTC-07:00) Arizona
US Mountain Standard Time

(UTC-07:00) Hora de las Montañas Rocosas (EE.UU. y Canadá)
Mountain Standard Time

(UTC-07:00) La Paz, Mazatlán
Mountain Standard Time (Mexico)

(UTC-07:00) Yukon
Yukon Standard Time

(UTC-06:00) América Central
Central America Standard Time

(UTC-06:00) Guadalajara, Ciudad de México, Monterrey
Central Standard Time (Mexico)

(UTC-06:00) Hora central (EE.UU. y Canadá)
Central Standard Time

(UTC-06:00) Isla de Pascua
Easter Island Standard Time

(UTC-06:00) Saskatchewan
Canada Central Standard Time

(UTC-05:00) Bogotá, Lima, Quito, Rio Branco
SA Pacific Standard Time

(UTC-05:00) Chetumal
Eastern Standard Time (Mexico)

(UTC-05:00) Haití
Haiti Standard Time

(UTC-05:00) Hora del este (EE.UU. y Canadá)
Eastern Standard Time

(UTC-05:00) Indiana (este)
US Eastern Standard Time

(UTC-05:00) Islas Turcas y Caicos
Turks And Caicos Standard Time

(UTC-05:00) La Habana
Cuba Standard Time

(UTC-04:00) Asunción
Paraguay Standard Time

(UTC-04:00) Caracas
Venezuela Standard Time

(UTC-04:00) Cuiabá
Central Brazilian Standard Time

(UTC-04:00) Georgetown, La Paz, Manaos, San Juan
SA Western Standard Time

(UTC-04:00) Hora del Atlántico (Canadá)
Atlantic Standard Time

(UTC-04:00) Santiago
Pacific SA Standard Time

(UTC-03:30) Terranova
Newfoundland Standard Time

(UTC-03:00) Araguaína
Tocantins Standard Time

(UTC-03:00) Brasilia
E. South America Standard Time

(UTC-03:00) Cayena, Fortaleza
SA Eastern Standard Time

(UTC-03:00) Ciudad de Buenos Aires
Argentina Standard Time

(UTC-03:00) Groenlandia
Greenland Standard Time

(UTC-03:00) Montevideo
Montevideo Standard Time

(UTC-03:00) Punta Arenas
Magallanes Standard Time

(UTC-03:00) Salvador
Bahia Standard Time

(UTC-03:00) San Pedro y Miquelón
Saint Pierre Standard Time

(UTC-02:00) Hora universal coordinada-02
UTC-02

(UTC-01:00) Azores
Azores Standard Time

(UTC-01:00) Cabo Verde
Cape Verde Standard Time

(UTC) Hora universal coordinada
UTC

(UTC+00:00) Dublín, Edimburgo, Lisboa, Londres
GMT Standard Time

(UTC+00:00) Monrovia, Reikiavik
Greenwich Standard Time

(UTC+00:00) Santo Tomé
Sao Tome Standard Time

(UTC+01:00) Casablanca
Morocco Standard Time

(UTC+01:00) África Central Occidental
W. Central Africa Standard Time

(UTC+01:00) Amsterdam, Berlín, Berna, Roma, Estocolmo, Viena
W. Europe Standard Time

(UTC+01:00) Belgrado, Bratislava, Budapest, Liubliana, Praga
Central Europe Standard Time

(UTC+01:00) Bruselas, Copenhague, Madrid, París
Romance Standard Time

(UTC+01:00) Sarajevo, Skopie, Varsovia, Zagreb
Central European Standard Time

(UTC+02:00) Atenas, Bucarest
GTB Standard Time

(UTC+02:00) Beirut
Middle East Standard Time

(UTC+02:00) Chisinau
E. Europe Standard Time

(UTC+02:00) Damasco
Syria Standard Time

(UTC+02:00) El Cairo
Egypt Standard Time

(UTC+02:00) Gaza, Hebrón
West Bank Standard Time

(UTC+02:00) Harare, Pretoria
South Africa Standard Time

(UTC+02:00) Helsinki, Kiev, Riga, Sofía, Tallin, Vilna
FLE Standard Time

(UTC+02:00) Jartum
Sudan Standard Time

(UTC+02:00) Jerusalén
Israel Standard Time

(UTC+02:00) Kaliningrado
Kaliningrad Standard Time

(UTC+02:00) Trípoli
Libya Standard Time

(UTC+02:00) Windhoek
Namibia Standard Time

(UTC+02:00) Yuba
South Sudan Standard Time

(UTC+03:00) Ammán
Jordan Standard Time

(UTC+03:00) Bagdad
Arabic Standard Time

(UTC+03:00) Estambul
Turkey Standard Time

(UTC+03:00) Kuwait, Riad
Arab Standard Time

(UTC+03:00) Minsk
Belarus Standard Time

(UTC+03:00) Moscú, San Petersburgo
Russian Standard Time

(UTC+03:00) Nairobi
E. Africa Standard Time

(UTC+03:00) Volgogrado
Volgograd Standard Time

(UTC+03:30) Teherán
Iran Standard Time

(UTC+04:00) Abu Dabi, Mascate
Arabian Standard Time

(UTC+04:00) Astrakhan, Ulyanovsk
Astrakhan Standard Time

(UTC+04:00) Bakú
Azerbaijan Standard Time

(UTC+04:00) Ereván
Caucasus Standard Time

(UTC+04:00) Izhevsk, Samara
Russia Time Zone 3

(UTC+04:00) Port Louis
Mauritius Standard Time

(UTC+04:00) Sarátov
Saratov Standard Time

(UTC+04:00) Tiflis
Georgian Standard Time

(UTC+04:30) Kabul
Afghanistan Standard Time

(UTC+05:00) Asjabad, Tashkent
West Asia Standard Time

(UTC+05:00) Ekaterimburgo
Ekaterinburg Standard Time

(UTC+05:00) Islamabad, Karachi
Pakistan Standard Time

(UTC+05:00) Qyzylorda
Qyzylorda Standard Time

(UTC+05:30) Chennai, Kolkata (Calcuta), Mumbai, Nueva Delhi
India Standard Time

(UTC+05:30) Sri Jayawardenepura
Sri Lanka Standard Time

(UTC+05:45) Katmandú
Nepal Standard Time

(UTC+06:00) Astaná
Central Asia Standard Time

(UTC+06:00) Dacca
Bangladesh Standard Time

(UTC+06:00) Omsk
Omsk Standard Time

(UTC+06:30) Yangón (Rangún)
Myanmar Standard Time

(UTC+07:00) Bangkok, Hanói, Yakarta
SE Asia Standard Time

(UTC+07:00) Barnaul, Gorno-Altaysk
Altai Standard Time

(UTC+07:00) Hovd
W. Mongolia Standard Time

(UTC+07:00) Krasnoyarsk
North Asia Standard Time

(UTC+07:00) Novosibirsk
N. Central Asia Standard Time

(UTC+07:00) Tomsk
Tomsk Standard Time

(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
China Standard Time

(UTC+08:00) Irkutsk
North Asia East Standard Time

(UTC+08:00) Kuala Lumpur, Singapur
Singapore Standard Time

(UTC+08:00) Perth
W. Australia Standard Time

(UTC+08:00) Taipéi
Taipei Standard Time

(UTC+08:00) Ulán Bator
Ulaanbaatar Standard Time

(UTC+08:45) Eucla
Aus Central W. Standard Time

(UTC+09:00) Chita
Transbaikal Standard Time

(UTC+09:00) Osaka, Sapporo, Tokio
Tokyo Standard Time

(UTC+09:00) Pyongyang
North Korea Standard Time

(UTC+09:00) Seúl
Korea Standard Time

(UTC+09:00) Yakutsk
Yakutsk Standard Time

(UTC+09:30) Adelaida
Cen. Australia Standard Time

(UTC+09:30) Darwin
AUS Central Standard Time

(UTC+10:00) Brisbane
E. Australia Standard Time

(UTC+10:00) Canberra, Melbourne, Sídney
AUS Eastern Standard Time

(UTC+10:00) Guam, Port Moresby
West Pacific Standard Time

(UTC+10:00) Hobart
Tasmania Standard Time

(UTC+10:00) Vladivostok
Vladivostok Standard Time

(UTC+10:30) Isla Lord Howe
Lord Howe Standard Time

(UTC+11:00) Chokurdakh
Russia Time Zone 10

(UTC+11:00) Isla Bougainville
Bougainville Standard Time

(UTC+11:00) Isla Norfolk
Norfolk Standard Time

(UTC+11:00) Islas Salomón, Nueva Caledonia
Central Pacific Standard Time

(UTC+11:00) Magadán
Magadan Standard Time

(UTC+11:00) Sajalín
Sakhalin Standard Time

(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky
Russia Time Zone 11

(UTC+12:00) Auckland, Wellington
New Zealand Standard Time

(UTC+12:00) Fiyi
Fiji Standard Time

(UTC+12:00) Hora universal coordinada+12
UTC+12

(UTC+12:45) Islas Chatham
Chatham Islands Standard Time

(UTC+13:00) Hora universal coordinada+13
UTC+13

(UTC+13:00) Nuku'alofa
Tonga Standard Time

(UTC+13:00) Samoa
Samoa Standard Time

(UTC+14:00) Isla Kiritimati
Line Islands Standard Time
```

**Comment by Deses** [comment]
It's working!!!!

**Comment by simulot** [comment]
The difficulty is when go-immich is compiled on windows targeting windows, the time zone is correctly handled. 
But when the program is compiled on linux, targeting windows, the program detect the windows TZ: the infamous Romance Time Zone, infers correctly the Europe/Paris, but the last one is unknown...

The trick was to embed the linux TZ definition files in the exe file... This works, only if this change is merged to the main before releasing it... Shame on me for that one.

**Comment by Deses** [comment]
I ran the upload process to my dad's 45 gb takeout and I'm positive it was pretty much flawless. It created all the albums and all the albums had a matching number of files.
Except one album that was missing one picture and it wasn't even present in the takeout to begin with.

With that I learned that the takeout file Google generates is not 100% reliable. I shudder when I think what kind of hellish file structure they have to miss some files.

**Comment by Deses** [comment]
In the logs, I removed all the lines that contain `This a new asset, upload it.` and `uploaded[39m` using Notepad++.
```
[37mIMG-20220911-WA0009.jpg: This a new asset, upload it.[39m
[32mUploading "Takeout/Google Fotos/Photos from 2022/IMG-20220911-WA0009.jpg"...[32mDone, total 8 uploaded[39m
```

And all I had left were a bunch (31) of lines like these:
`[37m20160306_165137_HDR.jpg: An asset with the same name:"20160306_165137_HDR" and date:"2016-03-06 16:51:36" but with smaller size:2.5 MB exists on the server. Replace it.[39m
``

That are duplicate files, one in a `Photos from 20XX` folder and the other in al album folder.

I've checked them and for the pictures they are fine, but I found an edge case:

One of the videos is one of those variable slowmo videos that are play at normal speed, then slomo for an user defined period and then back to normal. And the duplicated one is a full slowmo video.
This means that the app keeps only the biggest, full slowmo video.

**Comment by simulot** [comment]
> I ran the upload process to my dad's 45 gb takeout and I'm positive it was pretty much flawless. It created all the albums and all the albums had a matching number of files.

The project is now battle field proven... Thank you for this extensive test. I'm glad this went well.

> One of the videos is one of those variable slowmo videos that are play at normal speed, then slomo for an user defined period and then back to normal. And the duplicated one is a full slowmo video.
> This means that the app keeps only the biggest, full slowmo video.

Even you have found a workaround, it deserve opening a new issue with all details to help me to reproduce the problem, and maybe fixing it.
